#define FILE_DEVICE_XXX     0x0000800b

//IOCTL_CODE

#define IOCTL_XXX_YYY					(ULONG) CTL_CODE(FILE_DEVICE_XXX, 0x8001, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_NOTIFY_DRIVER_RESULT		(ULONG) CTL_CODE(FILE_DEVICE_XXX, 0x8002, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_XXX_ATTACK				(ULONG) CTL_CODE(FILE_DEVICE_XXX, 0x8003, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_TRANSFER_TYPE( _iocontrol)   (_iocontrol & 0x3)

