#define FILE_DEVICE_SANDBOX     0x0000800b

//IOCTL_CODE

#define IOCTL_XXX_YYY      (ULONG) CTL_CODE(FILE_DEVICE_SANDBOX, 0x8001, METHOD_BUFFERED, FILE_WRITE_ACCESS)
#define IOCTL_TRANSFER_TYPE( _iocontrol)   (_iocontrol & 0x3)

